### PR TITLE
Fix 138 : File field single file required UX

### LINKED ISSUE #138: Wrong error message when dropping 2 files on non multiple file field
When dropping 2 files onto this File Field case : 

```
<Field name="file.single" type="file" multiple={false} required>
  Only 1 file please
</Field>
```

The error message displayed is `Please select a valid file.` and it's confusing.

Also 1 file is kept as preview but the field is in error state so cannot be submitted.

https://github.com/user-attachments/assets/4528e63d-4d48-40d4-ae94-ad82fb497ced

### PR DESCRIPTION
**Pull request by glepretre**
Show specific error message when dropping more than 1 file on non-multiple file field and add demo

https://github.com/user-attachments/assets/61b55938-6ec9-438c-8f2d-036e8f211a41

Fixes #138

### CODE REVIEW

**Comment by glepretre** [comment]
Mob : Waiting for UX validation from @annabellou

File: src/i18n/fr.js [hunk 1]
```diff
@@ -17,6 +17,7 @@ export default {
     rejected: 'Veuillez sélectionner un fichier valide.',
     rejectedMultiple: 'Certains de vos fichiers ne sont pas valides.',
     noFile: 'Aucun fichier',
+    singleOnly: 'Veuilez sélectionner un seul fichier',
```
Comment (annabellou) [inline src/i18n/fr.js:20]: Be careful with the spelling of "veuillez"

**Review by annabellou — CHANGES_REQUESTED** [review]
It's functional 👍

In addition to the spelling note, a CSS improvement suggestion :

on `Formol_FileField__placeholder` , change only this properties : 

```
align-items: center
padding: 1em
```

and on `Formol_FielField__placeholder > svg`, change only this property : 

`margin: 0 auto 0`

So you can go from this 

image

To this

image

The space depends on the parent container and not anymore on the svg.
